accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import SignUpView
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include("receipts.urls")),
    path('accounts/', include("accounts.urls")),
    path('', RedirectView.as_view(url=reverse_lazy("home")), name="homepage"),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptCreateView,
    ReceiptsListView,
    ExpenseCategoryList,
    AccountList,
    ExpenseCategoryCreateView,
    AccountCreateView,
)

urlpatterns = [
    path('', ReceiptsListView.as_view(), name="home"),
    path('create/', ReceiptCreateView.as_view(), name="create_receipt"),
    path('categories/create/', ExpenseCategoryCreateView.as_view(), name="create_category"),
    path('categories/', ExpenseCategoryList.as_view(), name="list_category"),
    path('accounts/create/', AccountCreateView.as_view(), name="create_account"),
    path('accounts/', AccountList.as_view(), name="list_accounts"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(default=timezone.now)
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
# Create your views here.

# Function Based Signup View
# def signup_user(request):
#     if request.method == 'POST':
#         form = UserCreationForm()
#         if form.is_valid():
#             form.save()
#             return redirect("home")
#         else:
#             form = UserCreationForm()
#     form = UserCreationForm()  
#     context = {
#         'form':form,
#     }
#     return render(request, "signup.html", context)

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("home")
    template_name = "signup.html"

receipts/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from receipts.models import Receipt, ExpenseCategory, Account

# Create your views here.


# It inherits from CreateView because it's about creating things
class ReceiptsListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/receipts_list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


# It inherits from CreateView because it's about creating things
class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create_receipt.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)


class ExpenseCategoryList(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expense_category_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/create_category.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_category")


class AccountList(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/create_account.html"
    fields = ['name', 'number']

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")

accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Signup</h1>
            <form method="post">
                {% csrf_token %} 
                {{ form.as_p }}
                <button type="submit">Signup</button>
              </form>
        </div>
    </main>
</body>
</html>

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <ul>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a href="{% url 'create_category'%}">Create Category</a></li>
            <li><a href="{% url 'create_account'%}">Create Account</a></li>
            <li><a href="{% url 'create_receipt'%}">Create Receipt</a></li>            
            {% else %}   
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
        {% block content %} 
        {% endblock content %}
    </main>
</body>

receipts/templates/receipts/account_list.html
{% extends 'base.html' %}
{% block content %}
<div>     
    <h1>Accounts</h1>
        <table>
            <thead>
                <th>Name</th>
                <th>Number</th>
                <th>Number of Receipts</th>
            </thead>
            <tbody>
                {% for account in account_list %}
                <tr>
                    <td>{{ account.name }}</td>
                    <td>{{ account.number }}</td>
                    <td>{{ account.receipts.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

receipts/templates/receipts/create_account.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %} 
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form> 
  </div>
{% endblock content %}

receipts/templates/receipts/create_category.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>Create Category</h1>
    <form method="post">
        {% csrf_token %} 
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form> 
  </div>
{% endblock content %}

receipts/templates/receipts/create_receipt.html
{% extends 'base.html' %}
{% block content %}
      <div>
        <h1>Create Receipt</h1>
          <form method="post">
            {% csrf_token %} 
            {{ form.as_p }}
            <button type="submit">Create</button>
          </form> 
      </div>
      {% endblock content %}

receipts/templates/receipts/expense_category_list.html
{% extends 'base.html' %}
{% block content %}
<div>     
    <h1>My Receipts</h1>
        <table>
            <thead>
                <th>Name</th>
                <th>Number of Receipts</th>
            </thead>
            <tbody>
                {% for category in expensecategory_list %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>{{ category.receipts.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

receipts/templates/receipts/receipts_list.html
{% extends 'base.html' %}
{% block content %}   
    <h1>My Receipts</h1>
        <table>
            <thead>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </thead>
            <tbody>
                {% for receipt in receipt_list %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date }}</td>
                    <td>{{ receipt.category.name }}</td>
                    <td>{{ receipt.account.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
{% endblock content %}